/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppOperationalRouteImport } from './routes/_app/operational'
import { Route as AppMovimentacoesRouteImport } from './routes/_app/movimentacoes'
import { Route as AppEstoqueRouteImport } from './routes/_app/estoque'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppAnalyticalRouteImport } from './routes/_app/analytical'
import { Route as AppProdutosIndexRouteImport } from './routes/_app/produtos.index'
import { Route as AppProdutosIdRouteImport } from './routes/_app/produtos.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOperationalRoute = AppOperationalRouteImport.update({
  id: '/operational',
  path: '/operational',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimentacoesRoute = AppMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticalRoute = AppAnalyticalRouteImport.update({
  id: '/analytical',
  path: '/analytical',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosIndexRoute = AppProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosIdRoute = AppProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytical': typeof AppAnalyticalRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/estoque': typeof AppEstoqueRoute
  '/movimentacoes': typeof AppMovimentacoesRoute
  '/operational': typeof AppOperationalRoute
  '/produtos/$id': typeof AppProdutosIdRoute
  '/produtos/': typeof AppProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytical': typeof AppAnalyticalRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/estoque': typeof AppEstoqueRoute
  '/movimentacoes': typeof AppMovimentacoesRoute
  '/operational': typeof AppOperationalRoute
  '/produtos/$id': typeof AppProdutosIdRoute
  '/produtos': typeof AppProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/analytical': typeof AppAnalyticalRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/movimentacoes': typeof AppMovimentacoesRoute
  '/_app/operational': typeof AppOperationalRoute
  '/_app/produtos/$id': typeof AppProdutosIdRoute
  '/_app/produtos/': typeof AppProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/analytical'
    | '/categorias'
    | '/dashboard'
    | '/estoque'
    | '/movimentacoes'
    | '/operational'
    | '/produtos/$id'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/analytical'
    | '/categorias'
    | '/dashboard'
    | '/estoque'
    | '/movimentacoes'
    | '/operational'
    | '/produtos/$id'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/analytical'
    | '/_app/categorias'
    | '/_app/dashboard'
    | '/_app/estoque'
    | '/_app/movimentacoes'
    | '/_app/operational'
    | '/_app/produtos/$id'
    | '/_app/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/operational': {
      id: '/_app/operational'
      path: '/operational'
      fullPath: '/operational'
      preLoaderRoute: typeof AppOperationalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movimentacoes': {
      id: '/_app/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AppMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytical': {
      id: '/_app/analytical'
      path: '/analytical'
      fullPath: '/analytical'
      preLoaderRoute: typeof AppAnalyticalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos/': {
      id: '/_app/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AppProdutosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos/$id': {
      id: '/_app/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof AppProdutosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticalRoute: typeof AppAnalyticalRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppMovimentacoesRoute: typeof AppMovimentacoesRoute
  AppOperationalRoute: typeof AppOperationalRoute
  AppProdutosIdRoute: typeof AppProdutosIdRoute
  AppProdutosIndexRoute: typeof AppProdutosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticalRoute: AppAnalyticalRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppMovimentacoesRoute: AppMovimentacoesRoute,
  AppOperationalRoute: AppOperationalRoute,
  AppProdutosIdRoute: AppProdutosIdRoute,
  AppProdutosIndexRoute: AppProdutosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
